language: crystal

script:
  - crystal build src/owocr.cr
  - crystal spec
  - crystal docs

notifications:
  email: false
  irc:
    channels:
      - "ircs://irc.esper.net:6697/#proximyst"
      - "ircs://irc.spi.gt:6697/#proximyst"
    on_success: always
    on_failure: always
    template:
      - "#%{build_number} (%{build_id}) -> %{repository_slug}/%{branch} (%{commit}, %{author}): %{commit_subject}"
      - "%{result} @ %{elapsed_time} - %{build_url}"
      - "Changes: %{compare_url}"

deploy:
  provider: pages
  keep-history: true
  skip-cleanup: false
  # Token is set in Travis dashboard
  github-token: $GITHUB_TOKEN
  local-dir: docs
  comitter-from-gh: true
  on:
    branch: master